# Generated by Django 3.2.4 on 2021-06-06 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('main_image', models.ImageField(upload_to='main_catering')),
                ('average_check', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('main_image', models.ImageField(upload_to='main_lodging')),
                ('average_check', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('main_image', models.ImageField(upload_to='main_place')),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='place')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facilities.place')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lodging')),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facilities.lodging')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCatering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catering')),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facilities.catering')),
            ],
        ),
        migrations.CreateModel(
            name='CommentPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='place', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='facilities.place')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lodging', to=settings.AUTH_USER_MODEL)),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='facilities.lodging')),
            ],
        ),
        migrations.CreateModel(
            name='CommentCatering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='catering', to=settings.AUTH_USER_MODEL)),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='facilities.catering')),
            ],
        ),
    ]
